c
c standard input/output files 
      

c some LJ stuff:
      open(13,file='./datafiles/input.d',status='old')
c 
c data files for REBO potential 
C 
      open(14,file='./datafiles/inter3d_iv_new.d',
     &status='old')
      open(15,file='./datafiles/inter2d_iv.d',
     &status='old')
      open(16,file='./datafiles/inter3dtors.d',
     &status='old')
      open(17,file='./datafiles/inter3d_h.d',
     &status='old')
      open(18,file='./datafiles/inter3d_ch.d',
     &status='old')
c 
c optional input/output files
c 


